---
# tasks file for hmpps-delius-core-apacheds-bootstrap

- name: Block inbound access on ldap_port until bootstrap is finished
  iptables:
    chain: INPUT
    protocol: tcp
    source: '!127.0.0.1'
    destination_port: '{{ ldap_port }}'
    jump: REJECT
    state: present
  become: yes

- when: is_consumer
  block:
    - name: Wait for provider/master node (initial delay)
      wait_for: timeout=60
      delegate_to: localhost
    - name: Wait for provider/master node
      shell: 'ldapwhoami -H {{ ldap_protocol }}://{{ provider_host }}:{{ ldap_port }} -D {{ bind_user }} -w ${bind_password}'
      retries: 360
      delay: 10
      register: result
      until: result.rc == 0
      environment:
        bind_password: '{{ bind_password }}'