---
# tasks file for hmpps-delius-core-apacheds-bootstrap

- name: (main) set tag to indicate deployment
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "Deploying - {{ ndelius_version }}"

- name: Set facts
  include: set-facts.yml

- name: Block LDAP port
  include: block-wait.yml

- name: Create service
  include: init-service.yml

- name: Copy files
  include: copy-files.yml

- name: Update admin password
  include: modify-admin.yml

- name: Update schema
  include: modify-schema.yml

- name: Import roles, groups and users
  include: import-data.yml

- name: Create test users
  include: test-users.yml

- name: Setup replication
  include: replication.yml

- name: Backup script
  include: backups.yml

- name: Unblock LDAP port
  include: unblock.yml

- name: (main) set tag to indicate deployed ndelius_version
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "{{ ndelius_version }}"
