---
# tasks file for hmpps-delius-core-apacheds-bootstrap

- name: Create partition & import schema
  become: yes
  become_user: apacheds
  shell: 'ldapadd {{ ldap_connection }} -f {{ workspace }}/{{ item.file }}'
  environment:
    bind_password: '{{ bind_password }}'
  with_items:
    - { file: partition.ldif }
    - { file: schema.ldif }
    - { file: pwm-schema.ldif }
    - { file: interceptor.ldif }

- name: Replace Base64-encoded creatorsName attribute in schema with plaintext value
  become: yes
  become_user: apacheds
  replace:
    path: '~/default/partitions/schema/ou=schema/{{ item.schema }}'
    regexp: 'creatorsName:: [\w\W\n]+?(.+?):'
    replace: 'creatorsName: {{ bind_user }}\n\1:'
  with_items:
    - { schema: cn=subschemasubentry.ldif }
    - { schema: cn=pwm.ldif }

- name: Modify existing schema objects
  become: yes
  become_user: apacheds
  shell: 'ldapmodify {{ ldap_connection }} -f {{ workspace }}/modify-schema.ldif'
  environment:
    bind_password: '{{ bind_password }}'

- name: Restart apacheds
  include: restart-apacheds.yml
