---
# tasks file for hmpps-delius-core-apacheds-bootstrap

- name: Get hostname
  shell: hostname
  register: hostname

- name: Set facts
  set_fact:
    ldap_connection: '-H {{ ldap_protocol }}://localhost:{{ ldap_port }} -D {{ bind_user }} -w ${bind_password}'
    partition_context_entry: 'dn:{{ base_root }}\ndc:{{ partition_id }}\nobjectclass:domain\nobjectclass:top'
    consumer_id: 'consumer-{{ hostname.stdout }}'
    base_users: 'cn=Users,{{ base_root }}'
    casenotes_user: "{{ lookup('aws_ssm', '/'+environment_name+'/'+project_name+'/apacheds/apacheds/casenotes_user', region=region) }}"
    oasys_user: "{{ lookup('aws_ssm', '/'+environment_name+'/'+project_name+'/apacheds/apacheds/oasys_user', region=region) }}"
    iaps_user: "{{ lookup('aws_ssm', '/'+environment_name+'/'+project_name+'/apacheds/apacheds/iaps_user', region=region) }}"
    dss_user: "{{ lookup('aws_ssm', '/'+environment_name+'/'+project_name+'/apacheds/apacheds/dss_user', region=region) }}"
    performance_test_user_password: "{{ lookup('aws_ssm', '/'+environment_name+'/'+project_name+'/apacheds/apacheds/performance_test_user_password', region=region) }}"

- name: Set more facts
  set_fact:
    base_service_users: 'cn=EISUsers,{{ base_users }}'
    base_roles: 'cn=ndRoleCatalogue,{{ base_users }}'
    base_rolegroups: 'cn=ndRoleGroups,{{ base_users }}'
